.gitignore, CHANGES.txt, generator/pom.xml, generator/schema2template-maven-plugin/pom.xml, generator/schema2template/pom.xml, odfdom/pom.xml, pom.xml, simple/pom.xml, taglets/pom.xml, validator/pom.xml, xslt-runner-task/pom.xml, xslt-runner/pom.xml
I have removed (hopefully) the final namings of Apache (aside the license) and updated the Maven pom.xml to a recent edition so the current [JDK 11 / 1.0.0-SNAPSHOT branch](https://github.com/svanteschubert/odftoolkit/tree/odf-changes) is using the same plugins as our JDK 8 master branch.
Our new mailing list is now available and added:
`<mailingList>`
``
`<post>dev@odftoolkit.org</post>`
`<subscribe>dev+subscribe@odftoolkit.org</subscribe>`
`<unsubscribe>dev+unsubscribe@odftoolkit.org</unsubscribe>`
`<archive>https://listarchives.odftoolkit.org/dev/</archive>`
`<name>dev.odftoolkit.org</name>`
`</mailingList>`
=> Maven cleanup

simple/src/main/java/org/odftoolkit/simple/text/list/List.java, simple/src/main/java/org/odftoolkit/simple/text/list/NumberedGreekLowerDecorator.java, simple/src/test/java/org/odftoolkit/simple/text/list/NumberedListTest.java
In the cobnstructor of NumberedGreekLowerDecorator the greek symbols 'alfa' and 'beta' had been got lost, probably for characterset reasons. Now they are written directly in utf-8.
=> numbering of sorted Lists with lower greek symbols did not work and is now repaired

odfdom/src/test/java/org/odftoolkit/odfdom/integrationtest/JarManifestIT.java, validator/src/test/java/org/odftoolkit/odfvalidator/jar/ITJarTest.java
Executing the "java" command uses the default JRE which might be older than what is used during ODFToolkit build (meaning the build fails).
So explicitly use the Java of the current JRE (as set with the JAVA_HOME env var).
=> Fix test failure when default java is older

odfdom/src/test/java/org/odftoolkit/odfdom/dom/example/LoadMultipleTimes.java
While browsing the tests, I stumbled upon some typos
=> Fix a few typos in LoadMultipleTimes test

odfdom/pom.xml, odfdom/src/main/java/org/odftoolkit/odfdom/pkg/rdfa/RDFaParser.java, pom.xml
This branch builds against the new java-rdfa-1.0.0-BETA1 release prepared by us.
Thus, it cleans up many dependency problems.
Additionally, it add OSGi bundle headers to the oodfdom jar file, which fixes #78
=> Odfdom osgi bundle

odfdom/src/main/java/org/odftoolkit/odfdom/doc/OdfDocument.java, odfdom/src/main/java/org/odftoolkit/odfdom/doc/OdfSpreadsheetDocument.java, odfdom/src/main/java/org/odftoolkit/odfdom/doc/table/OdfTable.java, odfdom/src/main/java/org/odftoolkit/odfdom/dom/OdfSchemaDocument.java, odfdom/src/test/java/org/odftoolkit/odfdom/doc/table/TableCellRangeTest.java, odfdom/src/test/java/org/odftoolkit/odfdom/doc/table/TableTest.java, odfdom/src/test/java/org/odftoolkit/odfdom/pkg/EmbeddedDocumentTest.java
ODS documents do not need a recursive search for the "tables". Adding additional API into getTables() and use that in the tests.
The old API is marked as Deprecated.
=> #62 OdfSpreadsheetDocument: getTables and getTableList

odfdom/src/main/java/org/odftoolkit/odfdom/incubator/search/TextNavigation.java
The new constructor is necessary if we want to use Pattern flags (like unicode support).     
Compiling the pattern only once should also improve performance a bit.     
(Also cleans up the file a bit)
By the way, the .editorConfig file specifies 4 spaces for indentation, but the file is indented with 2 spaces. Should it be reformatted?
Thanks for the toolkit by the way, I've used it quite a bit already for manipulating ods and odt, and it works (most of the time) like a charm!
=> Adds a Pattern constructor to TextNavigation

validator/pom.xml, validator/src/main/java/org/odftoolkit/odfvalidator/JarManifest.java, validator/src/main/java/org/odftoolkit/odfvalidator/Main.java, validator/src/main/webapp/jsp/validate.jsp
So that it's obvious to see what is deployed on odfvalidator.org.
Also print it in jar file when invoked with -V, because why not.
Use git-commit-id-plugin maven plugin for this.
=> validator: put git revision on main page of webapp

generator/schema2template/src/main/java/schema2template/model/PuzzlePiece.java, generator/schema2template/src/test/java/schema2template/example/odf/PuzzlePieceTest.java
This created nondeterministic and wrong results, somewhere in
reduceAttributes().
The reason appears to be that there are ordered containers like a
TreeSet<PuzzlePiece> in uniteDefinitionsWithEqualContent() involved
and the PuzzlePiece.compareTo() has a problem with overflow, so it
sometimes returns wrong results and then the TreeSet will be wrongly
sorted and it can't find some elements.
Just compare the integers properly and the result is deterministic.
(cherry picked from commit 335bab81ce988283d4418e4bdec4262c96073478)
=> ODFTOOLKIT-187: fix results of PuzzlePiece.extractPuzzlePieces()

odfdom/pom.xml, validator/pom.xml
To get rid of vulnerable dependency plexus-utils:jar:2.0.4
=> upgrade to git-commit-id-maven-plugin 5.0.0

README.md, docs/ReleaseNotes.html, docs/website-development.html, src/site/site/content/odftoolkit_website/ReleaseNotes.mdtext, src/site/site/content/odftoolkit_website/index.mdtext
I have finally updated the once broken reference in the README.md (which happened some time ago when the master branch was renamed).
The release 0.10.0 requires an update of the code generation, which contained several "unknown unknown" problems and took much longer than expected, see https://github.com/svanteschubert/odftoolkit/tree/odf12-codegen
(I have created a milestone last week and had to postpone the work to October due to a release from a different project of mine).
Note that the 1.0.0 release was renamed to 0.10.0 as the Java package module was not yet added and deemed as a minimum for =>JDK 9.
=> Renaming release references from upcoming not yet existing releases to existing beta & release candidates

pom.xml
No longer needed for Java 11 and above.
Also solves compilation problems for users who enforce
Java 9 modular compilation (https://github.com/tdf/odftoolkit/issues/54#issuecomment-968061438)
Closes #131.
=> Remove dependency to xml-apis:xml-apis.

odfdom/pom.xml
Fixes #142.
New dependencies:
```
[INFO] org.odftoolkit:odfdom-java:jar:0.11.0-SNAPSHOT
[INFO] +- xerces:xercesImpl:jar:2.12.1:compile
[INFO] +- xalan:serializer:jar:2.7.2:compile
[INFO] +- junit:junit:jar:4.13.2:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.apache.jena:jena-core:jar:4.3.0:compile
[INFO] |  +- org.apache.jena:jena-base:jar:4.3.0:compile
[INFO] |  |  +- org.apache.jena:jena-shaded-guava:jar:4.3.0:compile
[INFO] |  |  +- org.apache.commons:commons-csv:jar:1.9.0:compile
[INFO] |  |  +- commons-io:commons-io:jar:2.11.0:compile
[INFO] |  |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  |  \- com.github.andrewoma.dexx:collection:jar:0.7:compile
[INFO] |  +- org.apache.jena:jena-iri:jar:4.3.0:compile
[INFO] |  \- …
```
=> Remove spurious dependencies to org.json and git-commit-id-maven plugin.

.github/workflows/deployment.yml, .github/workflows/maven.yml, odfdom/pom.xml, pom.xml, validator/pom.xml
I have started looking into GitHub actions over the holidays and created GitHub action that makes an automatic GitHub deployment whenever a Git tag is being added. 
For example:
- git tag -sm 0.11.0-SNAPSHOT 0.11.0-SNAPSHOT
- git push --follow-tags
results to https://github.com/svanteschubert/odftoolkit/releases/tag/odftoolkit-0.11.0-SNAPSHOT
(Note: I used a test tag 0.10.11 instead of 0.11.0-SNAPSHOT, but the version is being extracted in the action from the pom)
If someone does not like the commit message as part of the title (like me), it still seems an easy manual tweak - as I have not found out how this is handled by the plugin https://github.com/svenstaro/upload-release-action I am using. ;-)
There was once an official GitHub plugin, but this is for some unknown reason no longer …
=> Automated GitHub Deployment by GitHub Action

odfdom/src/main/java/org/odftoolkit/odfdom/incubator/doc/office/OdfStylesBase.java
Hi,
The visibility for the function is not indicated I think it is an oversight as all the others are public.
=> getTextStyle has not public function visibility

odfdom/src/main/java/org/odftoolkit/odfdom/changes/ChangesFileSaxHandler.java, odfdom/src/main/java/org/odftoolkit/odfdom/changes/FieldMap.java, odfdom/src/main/java/org/odftoolkit/odfdom/changes/MapHelper.java, odfdom/src/main/java/org/odftoolkit/odfdom/doc/OdfDocument.java, odfdom/src/main/java/org/odftoolkit/odfdom/pkg/OdfNamespace.java, odfdom/src/main/java/org/odftoolkit/odfdom/pkg/OdfPackage.java, odfdom/src/main/java/org/odftoolkit/odfdom/pkg/OdfXMLFactory.java, odfdom/src/main/java/org/odftoolkit/odfdom/pkg/manifest/OdfFileEntry.java, odfdom/src/main/java/org/odftoolkit/odfdom/type/Color.java
Hopefully the OdfNamespace one won't grow to any measurable size, otherwise will have to be moved somewhere non-static.
=> clean up static Map/Set/etc to avoid races and leaks

validator/pom.xml
Neither the .war file nor the -with-dependencies.jar file can be easily reused as a Maven dependency; let's try if this works better.
=> Fixes #215: validator: build additional plain jar file

validator/pom.xml
Realized there the package of the main class was wrong when I tested the JAR of the SNAPSHOT:
https://oss.sonatype.org/content/repositories/snapshots/org/odftoolkit/odfvalidator/0.12.0-SNAPSHOT/odfvalidator-0.12.0-20230525.140541-5-classes.jar
=> Fixing package name for validator main class

odfdom/src/main/java/org/odftoolkit/odfdom/incubator/search/Navigation.java, odfdom/src/main/java/org/odftoolkit/odfdom/incubator/search/TextNavigation.java, odfdom/src/main/java/org/odftoolkit/odfdom/incubator/search/TextStyleNavigation.java, odfdom/src/test/java/org/odftoolkit/odfdom/doc/table/TableRowColumnTest.java, odfdom/src/test/java/org/odftoolkit/odfdom/incubator/search/MONPTest.java, odfdom/src/test/java/org/odftoolkit/odfdom/incubator/search/TextNavigationTest.java, odfdom/src/test/java/org/odftoolkit/odfdom/incubator/search/TextSelectionTest.java, odfdom/src/test/java/org/odftoolkit/odfdom/incubator/search/TextStyleNavigationTest.java
This is a smaller improvement of the `org.odftoolkit.odfdom.incubator.search.Navigation` Interface.  
Using this feature in my own project I recognized that the `TextNavigation` was not working correctly - especially in case the search pattern occur multiple times in one document or paragraph. 
The following example shows how to replace all matches of a regex with a text using the new implementation:
```java
private void replaceODFTextFragment(OdfTextDocument doc, String pattern, String replace)
throws InvalidNavigationException {
try {			
TextNavigation searchPattern = new TextNavigation(pattern, doc);
while (searchPattern.hasNext()) {
OdfElement element = searchPattern.next(); //.getCurrentItem().getElement();
String text=element.getTextContent();
logger.info(" Current Item …
```
=> Improved navigation interface, added next() method

odfdom/pom.xml, pom.xml
Apply patch proposed by Boarschti42 to remove incorrect version constraints. (Possibly they were added at a time when the version number was 1.0.0-BETA...)
=> Fixes #254: ODFDOM: remove OSGI version constraints

odfdom/pom.xml, pom.xml, validator/pom.xml, xslt-runner/pom.xml
Updating dependencies before release
=> Updating dependencies

odfdom/src/main/java/org/odftoolkit/odfdom/doc/table/OdfTable.java
According to the ODF 1.3 spec, repeated columns cannot contain cells which span multiple rows or columns and repeated rows cannot contain vertical merges. Therefore, we can skip repeated rows and columns after the first one while searching for covering cells.
Note that while this code should properly handle horizontal merges in repeated rows, such merges are ignored after the first instance of the repeated row in current versions of LibreOffice, OpenOffice, and Excel, so this scenario is unlikely to come up.
=> Fix #285: Skip repeated rows and columns when possible

odfdom/src/test/java/org/odftoolkit/odfdom/changes/RoundtripTestHelper.java
JSON references - when cloned via Git on Windows receive sometimes a Windows line-ending (dependent on git configuration), which causes trouble (test errors - false positive) when comparing test results line-based.
The JSON created from the ODTs during regression tests is always created with Linux line endings.
Therefore, the line endings of reference test files are being changed from Windows to Linux to avoid this uncertainty.
=> Line-ending normalizsation for ODF JSON regression tests

docs/release-guide.html, src/site/site/content/odftoolkit_website/release-guide.mdtext
Enhancement of release documentation (another iteration after Sonatyp's configuration changes)
=> Update on release documentation

validator/src/main/java/org/odftoolkit/odfvalidator/MetaInformation.java
Apparently this was always wrong, and nobody used -g?
=> Fixes #319: validator: the generator element is in meta.xml

odfdom/src/main/java/org/odftoolkit/odfdom/pkg/OdfXMLFactory.java
I am currently developing an application that generates lots of documents in parallel. While profiling I noticed a bottleneck in `OdfXMLFactory#getOdfNodeClass`.
Since almost all entries of the Class cache are known after reading some documents, it should be possible to reduce locking and therefore increase parallelism. I firstly tried replacing the `synchronized`-Blocks with a RW-Lock, which resulted in slightly slower execution times. Using a ConcurrentHashMap however almost doubled the document throughput in my application.
Therefore I propose the changes in the commit.
=> Use ConcurrentMap instead of synchronized for class cache

odfdom/pom.xml, odfdom/src/main/java/org/odftoolkit/odfdom/pkg/OdfPackage.java
This pull request fixes the problem with password-protected LibreOffice files described in Issue #138.
It is now possible to open files with the old Blowfish encryption as well as with the AES256-CBC encryption.
Unfortunately, I had to add BouncyCastle because I couldn't solve the problem with the existing libraries.
resolves #138
=> Support for AES256-CBC encryption

README.md
This pull request addresses confusion about the README page on GitHub, claiming the documentation is also on GitHub while it is actually a GitHub Pages site URL.
=> Clarify the location hosting the documentation

validator/src/main/java/org/odftoolkit/odfvalidator/ODFValidator.java, validator/src/main/webapp/WEB-INF/web.xml, validator/src/main/webapp/jsp/info/info.jsp, validator/src/main/webapp/jsp/validate.jsp
Adding ODF 1.4 GUI to the ODF Validator, making ODF 1.4 the new default, and 
doing some refactoring:
1. in info.jsp
* v1.2/1.3 becomes v1.2/1.3/1.4 
* v1.0/v1.1 becomes v1.0/1.1
* v1.1/v1.0 becomes v1.0/1.1
2. in validate.jsp
* order the versions consistently - became confusing...
=> Adding ODF 1.4 GUI to the ODF Validator

generator/schema2template/src/test/java/schema2template/grammar/DirectoryCompare.java, generator/schema2template/src/test/java/schema2template/grammar/GenerationOdfdomJavaTest.java, generator/schema2template/src/test/java/schema2template/grammar/MSVRunTimeDumpTest.java
I have changed the code that is used to compare directories:
- Instead of returning boolean values, it directly uses Assertion. methods to let JUnit do the formatting. I also renamed the methods from `compareDirectories()` to `assertDirectoriesEqual()` and made sure the order of parameters matches the standard order of the assert methods (expected result first, actual result second).
- When a difference in a text file is found, the original and changed lines are included in the assertion message.
- .DS_Store files are ignored - these files are created automatically by macOS when opening a directory in Finder; this means once you open a directory when looking for the cause of a failure, the tests will fail because now the number of files doesn't match and since these files are hidden by …
=> refactor file contents tests; ignore macOS .DS_Store files in tests

odfdom/src/main/java/org/odftoolkit/odfdom/doc/table/OdfTableCell.java, odfdom/src/test/java/org/odftoolkit/odfdom/doc/table/TableCellTest.java
This fixes #393 and contains the addition to the unit test as suggested by @PeterFokkinga .
=> fix getTimeValue()/setTimeValue()

.github/workflows/maven.yml, generator/schema2template/pom.xml, odfdom/pom.xml, pom.xml, taglets/pom.xml, validator/pom.xml, xslt-runner/pom.xml
This PR adds sonarqube scanning and code coverage. Getting JaCoCo to work correctly took some time -  but I think this is really important to have, otherwise we cannot easily tell if a change we integrate is covered by unit tests.
This is the first part of implementing #386. After integrating the PR, a secret has to be added in the GitHub configuration by the main maintainer for the scan to work. I have included the instructions on how to add in the linked issue.
These two lines in maven.yml have to be changed too to match the Sonar configuration:
-Dsonar.projectKey=xzel23_odftoolkit
-Dsonar.organization=xzel23
=> add sonarqube static analysis and jacoco code coverage

pom.xml, src/site/site/content/odftoolkit_website/docs/settings-example.xml, src/site/site/content/odftoolkit_website/release-guide.mdtext
Sonatype is retiring OSSRH and the namespace was migrated to Maven Central already.
Try to adapt docs and pom.xml with snippets copied from various docs and hope it will work...
[... just typed "mvn deploy" and the result is at https://central.sonatype.com/service/rest/repository/browse/maven-snapshots/org/odftoolkit/ ]
=> replace legacy OSSRH stuff with Central
